site_name: Pyresparser
site_description: A simple resume parser used for extracting information from resumes
nav:
    - Home: index.md
    - CLI: cli.md
repo_url: https://github.com/tahahasan01/pyresparser
site_author: Taha Hasan
google_analytics: ['UA-111548790-1', 'tahahasan.com']
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"

theme: readthedocs